### ISSUE TITLE
Is this a good repo to start from for generic PI-WebAPI programming? 

### ISSUE THREAD

**Issue by UGuntupalli** [osisoft/sample-pi_web_api-common_actions-python#17]
Hello @cbardini, 

I have just started to look at OSISoft tutorial channels and stumbled upon your repositories. I use Python and am starting to explore OSI PI. Is this the best repository for Python to get started with the PI Web API ?If there is a different wrapper repository or a good starting point to help with the generic authentication and efficient data extraction from PI Web API, can you kindly point me in that direction ? 

Thanks

**Comment by UGuntupalli** [comment]
@cbardini , 

Could you please let me know if there is a different package that might be a good starting point ?

**Comment by cbardini** [comment]
Hello @UGuntupalli,
This sample is generally a good starting point for data extraction through the PI Web API. The only other sample that we have that might be useful is https://github.com/osisoft/sample-pi_web_api-data_analysis_jupyter-python, which uses python in a jupyter notebook. Is there anything missing in the sample such that it does not address your use case?

**Comment by UGuntupalli** [comment]
No @cbardini. I was just looking to get started with PyWebAPI for work and wanted to make sure this was a good point to start from. This helps.
